name: Build and deploy docker

on:
  push:
    branches:
      - main
    paths:
      - '.docker/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV_PATH: staging
      ROOT_DIR: ${{ github.workspace }}
      GITHUB_TOKEN: ${{ secrets.GIT_PAT_TOKEN }}
      ASSETS_BUCKET: ${{ secrets.ASSETS_BUCKET }}
      TERRAFORM_KEY: ${{ secrets.TERRAFORM_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google credentials
        run: |
          echo -n "${TERRAFORM_KEY}" > "${ROOT_DIR}/google-credentials.json"
          echo "GOOGLE_CREDENTIALS_PATH=${ROOT_DIR}/google-credentials.json" >> $GITHUB_ENV

      - name: Build
        env:
          GOOGLE_CREDENTIALS_PATH: ${{ env.GOOGLE_CREDENTIALS_PATH }}
        run: |
          chmod +x "${ROOT_DIR}/terraform/environments/${ENV_PATH}/build.sh"
          "${ROOT_DIR}/terraform/environments/${ENV_PATH}/build.sh" --github-actions --docker-only
