name: Build and deploy staging

on:
  push:
    branches:
      - main
      - staging
      - component/github-actions
    paths:
      - 'docker/demo-image/'
      - 'terraform/environments/staging/'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV_PATH: staging
      ROOT_DIR: ${{ github.workspace }}
      # GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }} passed implicitly
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Google credentials
        run: |
          echo "${{ secrets.DEM_PRJ_S_GAS_G_TERRAFORM }}" > ${{ github.workspace }}/google-credentials.json
          echo "GOOGLE_CREDENTIALS_PATH=${{ github.workspace }}/google-credentials.json" >> $GITHUB_ENV
      - name: Push state
        run: ./terraform/environments/$ENV_PATH/build.sh
