name: Build and deploy staging

on:
  push:
    branches:
      - main
    paths:
      - '.github/'
      - 'docker/demo-image/'
      - 'terraform/environments/staging/'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV_PATH: staging
      ROOT_DIR: ${{ github.workspace }}
      GITHUB_TOKEN: ${{ secrets.GIHUB_TOKEN }}
      ASSETS_BUCKET: ${{ secrets.ASSETS_BUCKET }}
      TERRAFORM_SECRET_NAME: DEM_PRJ_S_GAS_G_TERRAFORM
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google credentials
        env:
          TERRAFORM_SECRET: ${{ secrets.DEM_PRJ_S_GAS_G_TERRAFORM }}
        run: |
          echo -n "${TERRAFORM_SECRET}" > "${ROOT_DIR}/google-credentials.json"
          echo "GOOGLE_CREDENTIALS_PATH=${ROOT_DIR}/google-credentials.json" >> $GITHUB_ENV

      - name: Push state
        env:
          GOOGLE_CREDENTIALS_PATH: ${{ env.GOOGLE_CREDENTIALS_PATH }}
        run: |
          chmod +x "${ROOT_DIR}/terraform/environments/${ENV_PATH}/build.sh"
          "${ROOT_DIR}/terraform/environments/${ENV_PATH}/build.sh"



# name: Build and deploy staging

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - '.github/'
#       - 'docker/demo-image/'
#       - 'terraform/environments/staging/'
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       ENV_PATH: staging
#       ROOT_DIR: ${{ github.workspace }}
#       ASSETS_BUCKET: ${{ secrets.ASSETS_BUCKET }}
#       TERRAFORM_SECRET_NAME: ${{ secrets.TERRAFORM_SECRET_NAME }}
#       # GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }} passed implicitly
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Set up Google credentials
#         env:
#           TERRAFORM_SECRET: {{ secrets[env.TERRAFORM_SECRET_NAME] }}
#         run: |
#           echo "${TERRAFORM_SECRET}" > "${ROOT_DIR}/google-credentials.json"
#           echo "GOOGLE_CREDENTIALS_PATH="${ROOT_DIR}/google-credentials.json" >> $GITHUB_ENV
#       - name: Push state
#         run: |
#           chmod +x "{$ROOT_DIR}/terraform/environments/${ENV_PATH}/build.sh"
#           "{$ROOT_DIR}/terraform/environments/${ENV_PATH}/build.sh"
